### ISSUE TITLE
Errors on executing the program

### ISSUE THREAD

**Issue by frahman2** [arminkz/AutomataGP#1]
Hi,

Please note that I've tried to execute the project, but I have the below errors. I am using MVS 2015. 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Assembly 'DataGrid2DLibrary' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.	AutomataGP	...\AutomataGP-master\AutomataGP-master\AutomataGP\MainWindow.xaml	7

Severity	Code	Description	Project	File	Line	Suppression State
Error		The name "DataGrid2D" does not exist in the namespace "clr-namespace:DataGrid2DLibrary;assembly=DataGrid2DLibrary".	AutomataGP	...\AutomataGP-master\AutomataGP-master\AutomataGP\MainWindow.xaml	157

Severity	Code	Description	Project	File	Line	Suppression State
Error		The type 'dg2d:DataGrid2D' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	AutomataGP	...\AutomataGP-master\AutomataGP-master\AutomataGP\MainWindow.xaml	157	

Regards,
firas

**Comment by arminkz** [comment]
Hello,

it was related to dependency to DataGrid2D Library that i used in my code , please read README.md , I've added link to the target library.

also im planning to make this library Nuget-Based soon.

Thanks very much for addressing this issue.
